#27 integrated mantle into app frontend

diff --git a/devops/sfy-link-in-bio-app/Dockerfile b/devops/sfy-link-in-bio-app/Dockerfile
--- a/devops/sfy-link-in-bio-app/Dockerfile
+++ b/devops/sfy-link-in-bio-app/Dockerfile
@@ -55,19 +55,22 @@ RUN turbo prune @repo/sfy-link-in-bio-app --docker
 FROM base AS builder
 
 # Build-time args for Vite environment variables
-ARG VITE_CLIENT_API_CORE_URL
+ARG VITE_API_CORE_URL
 ARG VITE_POSTHOG_KEY
 ARG VITE_POSTHOG_HOST
+ARG VITE_MANTLE_APP_ID
 
 # Validate required build args
-RUN test -n "$VITE_CLIENT_API_CORE_URL" || (echo "VITE_CLIENT_API_CORE_URL build arg is required" && false)
+RUN test -n "$VITE_API_CORE_URL" || (echo "VITE_API_CORE_URL build arg is required" && false)
 RUN test -n "$VITE_POSTHOG_KEY" || (echo "VITE_POSTHOG_KEY build arg is required" && false)
 RUN test -n "$VITE_POSTHOG_HOST" || (echo "VITE_POSTHOG_HOST build arg is required" && false)
+RUN test -n "$VITE_MANTLE_APP_ID" || (echo "VITE_MANTLE_APP_ID build arg is required" && false)
 
 # Set as system environment variables for the build
-ENV VITE_CLIENT_API_CORE_URL=$VITE_CLIENT_API_CORE_URL \
+ENV VITE_API_CORE_URL=$VITE_API_CORE_URL \
     VITE_POSTHOG_KEY=$VITE_POSTHOG_KEY \
-    VITE_POSTHOG_HOST=$VITE_POSTHOG_HOST
+    VITE_POSTHOG_HOST=$VITE_POSTHOG_HOST \
+    VITE_MANTLE_APP_ID=$VITE_MANTLE_APP_ID
 
 WORKDIR /app
 
