#develop vite config cleanup

diff --git a/devops/sfy-link-in-bio-app/Dockerfile b/devops/sfy-link-in-bio-app/Dockerfile
--- a/devops/sfy-link-in-bio-app/Dockerfile
+++ b/devops/sfy-link-in-bio-app/Dockerfile
@@ -55,6 +55,7 @@ RUN turbo prune @repo/sfy-link-in-bio-app --docker
 FROM base AS builder
 
 # Build-time args for Vite environment variables
+ARG SHOPIFY_APP_URL
 ARG VITE_API_CORE_URL
 ARG VITE_POSTHOG_KEY
 ARG VITE_POSTHOG_HOST
@@ -62,6 +63,7 @@ ARG VITE_MANTLE_APP_ID
 ARG VITE_CRISP_TOKEN
 
 # Validate required build args
+RUN test -n "$SHOPIFY_APP_URL" || (echo "SHOPIFY_APP_URL build arg is required" && false)
 RUN test -n "$VITE_API_CORE_URL" || (echo "VITE_API_CORE_URL build arg is required" && false)
 RUN test -n "$VITE_POSTHOG_KEY" || (echo "VITE_POSTHOG_KEY build arg is required" && false)
 RUN test -n "$VITE_POSTHOG_HOST" || (echo "VITE_POSTHOG_HOST build arg is required" && false)
@@ -69,7 +71,8 @@ RUN test -n "$VITE_MANTLE_APP_ID" || (echo "VITE_MANTLE_APP_ID build arg is requ
 RUN test -n "$VITE_CRISP_TOKEN" || (echo "VITE_CRISP_TOKEN build arg is required" && false)
 
 # Set as system environment variables for the build
-ENV VITE_API_CORE_URL=$VITE_API_CORE_URL \
+ENV SHOPIFY_APP_URL=$SHOPIFY_APP_URL \
+    VITE_API_CORE_URL=$VITE_API_CORE_URL \
     VITE_POSTHOG_KEY=$VITE_POSTHOG_KEY \
     VITE_POSTHOG_HOST=$VITE_POSTHOG_HOST \
     VITE_MANTLE_APP_ID=$VITE_MANTLE_APP_ID \
